### ISSUE TITLE
Nice work :)

### ISSUE THREAD

**Issue by oregonpillow** [jcul/bencode#1]
Stumbled across this after looking for packages to decode .torrent files and extract file name.
Yours is the simplest module/solution I found and your example in the readme is exactly what I wanted.

Glad you took the time to code this for fun 8 years ago =)

**Comment by jcul** [comment]
I'm glad you found it useful! :)
I didn't think anyone would ever use this, just goes to show it's worth sharing little things like this.

**Comment by oregonpillow** [comment]
Gave you a shout out : https://github.com/oregonpillow/Haugene-Mouse

**Comment by jcul** [comment]
Thanks.
MyAnonamouse! ❤️
